name: Release the lib to Hackage

on:
  push:
    branches:
      - supermajor
      - major
      - minor
      - patch

concurrency:
  group: cd
  cancel-in-progress: false

jobs:

  ci:
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  cd:
    needs:
      - ci
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Release
        uses: nikita-volkov/release-haskell-package.github-action@v1.1.0
        with:
          hackage-token: ${{ secrets.HACKAGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-bump-place: ${{ fromJSON('{"supermajor":0,"major":1,"minor":2,"patch":3}')[github.ref_name] }}
          main-branch: master
          prefix-tag-with-v: true
